### ISSUE TITLE
Función aplicar una penalización. Prioridad: 6

### ISSUE THREAD

**Issue by DenisaIo** [RaulJDlCRUZ/Lorem-Software#24]
**Como** bibliotecario

**Quiero** aplicar una penalización

**Para** que los usuarios que no hayan devuelto un ejemplar en la fecha límite establecida, no puedan solicitar más préstamos temporalmente

‌

**Valor:** 30.000 $

**Estimación de esfuerzo:** 3 días

Las penalizaciones a un cliente se aplican cuando este no devuelve un ejemplar de un libro a tiempo (pasado el periodo de préstamo), por lo tanto, este requisito depende del préstamo de un libro y de la devolución de este ejemplar.

Tareas de la función:

- Estimar control de errores y analizar flujo de eventos (15/12 - 15/12)
- Mapeo de controladores y generación de métodos de capa de dominio (15/12 - 16/12)
- Implementar interfaz de usuario (front-end) (16/12 - 18/12)
- Realizar pruebas (18/12 - 18/12)

**Comment by PabloBlazquezSanchez** [comment]
Tras implementar la funcionalidad, se ha añadido a la aplicación que se detecte si un usuario que va a hacer un préstamo tiene una penalización que finalice en una fecha posterior a la realización del préstamo, y que se impida que pueda realizar la operación.
